pull_request_rules:
    - name: automatic merge on CI success and 2 approved reviews
      conditions:
        - "#approved-reviews-by>=2"
        - "check-success=Test on Docker Before Merge / docker (pull_request)"
        - base=main
      actions:
        merge:
          method: rebase
    - name: automatic merge on CI success if only markdown and/or Golang files were changed
      conditions:
        - "check-success=Test on Docker Before Merge / docker (pull_request)"
        - files~=.\.(?i)(md|go)$
        - base=main
      actions:
        merge:
          method: rebase
