pull_request_rules:
    - name: automatic merge on CI success and 2 approved reviews
      conditions:
        - "#approved-reviews-by>=2"
        - base=main
        - check-success=lint
        - check-success=Analyze
        - check-success=Run code coverage via container
        - check-success=Run tests on various Go versions via container
        - check-success=Platform test (ubuntu-latest)
        - check-success=Platform test (macos-latest)
        - check-success=Platform test (windows-latest)
        - -draft
      actions:
        merge:
          method: squash
    - name: automatic merge on CI success if only markdown files were changed
      conditions:
        - files~=.\.(?i)(md)$
        - base=main
        - check-success=lint
        - check-success=Analyze
        - check-success=Run code coverage via container
        - check-success=Run tests on various Go versions via container
        - check-success=Platform test (ubuntu-latest)
        - check-success=Platform test (macos-latest)
        - check-success=Platform test (windows-latest)
        - -draft
      actions:
        merge:
          method: squash
    - name: Automatic merge on bot's PR (go.mod and go.sum updateonly)
      conditions:
        - author=KEINOS
        - base=main
        - title~=^Changes
        - files=go.mod
        - files=go.sum
        - "#files=2"
        - check-success=Analyze
        - check-success=Run code coverage via container
        - check-success=Run tests on various Go versions via container
        - check-success=Platform test (ubuntu-latest)
        - check-success=Platform test (macos-latest)
        - check-success=Platform test (windows-latest)
      actions:
        merge:
          method: merge