pull_request_rules:
    - name: automatic merge on CI success and 2 approved reviews
      conditions:
        - "#approved-reviews-by>=2"
        - "check-success=docker_test"
        - base=main
      actions:
        merge:
          method: squash
          strict: smart+fasttrack
    - name: automatic merge on CI success if only markdown and/or Golang files were changed
      conditions:
        - "check-success=docker_test"
        - files~=.\.(?i)(md|go)$
        - base=main
      actions:
        merge:
          method: squash
          strict: smart+fasttrack
