pull_request_rules:
    - name: automatic merge on CI success and 2 approved reviews
      conditions:
        - "#approved-reviews-by>=2"
        - "check-success=merge_tests"
        - base=main
        - -draft
      actions:
        merge:
          method: squash
          strict: smart+fasttrack
    - name: automatic merge on CI success if only markdown and/or Golang files were changed
      conditions:
        - "check-success=merge_tests"
        - files~=.\.(?i)(md|go)$
        - base=main
        - -draft
      actions:
        merge:
          method: squash
          strict: smart+fasttrack
    - name: Automatic merge on approval
      conditions:
        - author=KEINOS
        - base=main
        - title~=^Changes
        - files=go.mod
        - files=go.sum
        - "#files=2"
        - check-success=Analyze (go)
        - check-success=Run tests on Go via container
        - check-success=Platform test (ubuntu-latest)
        - check-success=Platform test (macos-latest)
        - check-success=Platform test (windows-latest)
      actions:
        merge:
          method: merge