/*
Package cmd rootCmd is a mother command of all it's child(subcommands).

Each subcommands should add(register) themselfs in their `init()` via
`rootCmd.AddCommand()`. See other command packages' `init()` func.
*/
package cmd

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

/*
===============================================================================
 Root command
===============================================================================
*/

// rootCmd represents the base command when called without any subcommands
var rootCmd = &cobra.Command{
	Use:   "Hello-Cobra",
	Short: "Sample command of Cobra usage.",
	Long: `About:
	Simple CLI app to see how Cobra works to create commands.`,
}

// Set global flags and configuration of the app(rootCmd)
func init() {
	// Maybe we should implement this with a test someday.
	//rootCmd.PersistentFlags().StringVar(&cfgFile, "config", "", "config file (default is $HOME/.Hello-Cobra.yaml)")

	// The default local flag that's been generated by Cobra. Which does nothing.
	rootCmd.Flags().BoolP("toggle", "t", false, "Global command option but does nothing.")
}

/*
===============================================================================
 Exported functions of cmd package. https://tour.golang.org/basics/3
===============================================================================
 Define functions that are used through out the `cmd` and `main` package here.
*/

// Echo is an alias of `Println` to ease testing or mock the output.
func Echo(msg string) {
	fmt.Println(msg)
}

// EchoIfError is an STDERR wrappter. Returns a bool to let main.go take
// controll to exit. Note that its input type is `error` and not `string`.
func EchoIfError(msg error) int {
	if msg != nil {
		fmt.Fprintln(os.Stderr, msg)
		return 1
	}
	return 0
}

// Execute adds all child commands to the root command and sets flags appropriately.
// This is called by main.main(). It only needs to happen once to the rootCmd.
// Returns `error` when it fails to execute.
func Execute() error {
	return rootCmd.Execute()
}
