name: Tests before merge

on:
  workflow_dispatch:
  pull_request:

jobs:
  docker_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the test image
        run: |
          pwd && \
          cd ./.devcontainer && \
          docker build -t test:ci .
      - name: Run the tests on the container
        run: |
          pwd && \
          docker run \
            -v $(pwd):/workspaces/Hello-Cobra \
            -w /workspaces/Hello-Cobra \
            test:ci \
            /bin/bash ./.github/run-tests-merge.sh
